/**
 * ESM resolve hooks for the Node test runner (`test/run-node.mjs`).
 *
 * The test suites import the browser-target WASM modules generated by
 * `npm run build:test` (`test/wasm/crypto/crypto.js`, `test/wasm/cypher/cypher.js`).
 * Those files need wasm-pack + clang, so PRs should not have to build them.
 * These hooks redirect those two specifiers to the committed Node shims in
 * `test/node/`, which re-export the committed bundler-target WASM builds.
 */
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));

const REDIRECTS = new Map([
  ["./wasm/crypto/crypto.js", pathToFileURL(path.join(here, "wasm-crypto.mjs")).href],
  ["./wasm/cypher/cypher.js", pathToFileURL(path.join(here, "wasm-cypher.mjs")).href],
]);

/** @param {string} specifier @param {import("node:module").ResolveContext} context */
export async function resolve(specifier, context, nextResolve) {
  const target = REDIRECTS.get(specifier);
  if (target !== undefined) {
    return { url: target, format: "module", shortCircuit: true };
  }
  return nextResolve(specifier, context);
}
